import Navbar from './components/Navbar';
import { Inter } from 'next/font/google';
import { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: "Peter's Blog",
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className='bg-slate-800'>
				<Navbar />
				<main
					className='px-4 text-white/1 md:px-6 prose prose-xl prose-slate  dark:prose-invert mx-auto'
					style={{ color: 'white' }}
				>
					{children}
				</main>
			</body>
		</html>
	);
}
